{"Action":"POST","ErrorCode":500,"ErrorMessage":"","URL":"http://cy2caut01:5000/api/v1/testrun","Body":"{\"Id\":0,\"Name\":\"Hertz_Runs\",\"Environment\":\"QA A\",\"FrameworkVersion\":\"1.0.1.9\",\"FkClientId\":3,\"User\":\"rvastrad\",\"GUID\":\"9383325a_3d7e_4aa7_bf8e_b83aa6b07745\",\"StartTime\":\"2020-02-11T11:04:04.536599-06:00\",\"JiraKeys\":[]}","Message":"Exception of type 'Brierley.TestAutomation.Core.Reporting.RestReportingException' was thrown.","Data":{},"InnerException":null,"StackTrace":"   at Brierley.TestAutomation.Core.Reporting.RestReport.<ExecuteRequestAsync>d__13.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Brierley.TestAutomation.Core.Reporting.RestReport.<CreateTestRunAsync>d__4.MoveNext()","HelpLink":null,"Source":"Brierley.TestAutomation.Core.Reporting","HResult":-2146233088}